In [1]:
import pyromat as pm

In [2]:
air = pm.get('ig.air')

In [3]:
air.gam(T=[300, 400, 500, 600])

array([1.39991606, 1.39477137, 1.38641678, 1.37600618])

The properties include

`cp` Isobaric specific heat <br/>
`cv` Isochoric specific heat <br/>
`d` Density <br/>
`e` Internal energy <br/>
`gam` Specific heat ratio <br/>
`h` Enthalpy <br/>
`mw` Molecular weight <br/>
`R` Ideal gas constant <br/>
`s` Entropy <br/>

In [5]:
# pm.info()

In [6]:
N2 = pm.get('ig.N2')
O2 = pm.get('ig.O2')
CO2 = pm.get('ig.CO2')

In [7]:
# Getting molecular weight
N2.mw()

28.01348

In [8]:
N2.h(T=496.5, p=3.)     # T and p as explicit keywords

array([207.43522083])

In [9]:
N2.h(T=496.5)           # p is omitted; h is not a function of p

array([207.43522083])

In [10]:
N2.h(496.5, 3.)         # T and p as ordered arguments (T comes first)

array([207.43522083])

In [11]:
N2.h(496.5)             # p is omitted; h is not a function of p

array([207.43522083])

## Working with units

In [12]:
N2.s(T=700.,p=50.)

array([6.58052595])

In [13]:
pm.config['unit_temperature'] = 'F'

In [14]:
N2.s(T=800.33,p=50.)*1.8    # 800.33F == 700K

array([6.58052595])

`pm.config` ==  default setting-nya adalah sebagai berikut:<br/>
... <br/>
     `unit_energy` : 'kJ' <br/>
      `unit_force` : 'N' <br/>
     `unit_length` : 'm' <br/>
       `unit_mass` : 'kg' <br/>
     `unit_matter` : 'kg' <br/>
      `unit_molar` : 'kmol' <br/>
   `unit_pressure` : 'bar' <br/>
`unit_temperature` : 'K' <br/>
       `unit_time` : 's' <br/>
     `unit_volume` : 'm3' <br/>
...

In [15]:
N2.mw()

28.01348

In [16]:
N2.s()

array([3.99756896])

In [17]:
pm.config['unit_matter'] = 'kmol'
N2.s()

array([111.98581814])

In [22]:
pm.units.show()

AttributeError: 'dict' object has no attribute 'iteritems'

## Working with arrays

In [23]:
import numpy as np

In [24]:
T = np.arange(300., 1000.,100.) #start, finish, number of points
N2.h(T)

array([ 3618.21263508,  5252.39756517,  6898.08026197,  8558.17994855,
       10235.34538703, 11931.80610157, 13649.22360133])

In [25]:
T = np.array([500., 550., 600.]);
p = 40.5;
N2.s(T,p)

array([ 98.82107136,  99.66220196, 100.46648834])

[Making surface plots](http://pyromat.org/doc_howto.html#plot_surf); [the code is here](http://pyromat.org/src/steamtest.py)

In [26]:
#
#   Steam phase change demo
#   By Chris Martin (c) 2016
#   GPL v3.0
#   Enjoy!
#
# In this code, we generate a surface plot that spans the saturation
# curve from triple point to critical point.  We'll add two red lines
# to show where the liquid- and gas-phase saturation properties are in 
# each plot.  

import pyromat as pyro
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np


# Start with a blank slate
plt.close('all')

# Get the steam object
S = pyro.get('mp.H2O')

# Get the critical and triple point properties
Tt,pt = S.triple()
Tc,pc = S.critical()

# Explore the temperatures between Tt and Tc in 5K increments
Ts = np.arange(Tt,Tc,5.)

# Now, obtain the saturation properties
# Note that when a saturation property is called with the "tp" flag True
# it also returns the saturation temperature and pressure.
# This is more efficient than separate calls to Ts and ps.
Ts,ps,dL,dV = S.ds(T=Ts,tp=True)
# It is faster to explicitly pass both Ts and ps to the saturation methods.
# This saves them a redundant call to Ts or ps since both are required anyway.
hL,hV = S.hs(T=Ts,p=ps)
sL,sV = S.ss(T=Ts,p=ps)
eL,eV = S.es(T=Ts,p=ps)
# Note that this code results in warnings that the accuracy of saturation
# properties is reduced above 623.15K.  This is normal; PYro is simply 
# making sure the user is aware that saturation properties in this region 
# can be difficult to provide accurately.

# Now, crank out some surface plots
T,p = np.meshgrid(Ts,ps)

# Calculate density, enthalpy, entropy, and internal energy
d = S.d(T,p)
h = S.h(T,p)
s = S.s(T,p)
e = S.e(T,p)


f = plt.figure(1)
ax = f.add_subplot(111,projection='3d')
ax.plot_surface(T,p,d)
ax.plot(Ts,ps,dL,'r')
ax.plot(Ts,ps,dV,'r')
ax.set_xlabel('T')
ax.set_ylabel('p')
ax.set_zlabel('density')

f = plt.figure(2)
ax = f.add_subplot(111,projection='3d')
ax.plot_surface(T,p,h)
ax.plot(Ts,ps,hL,'r')
ax.plot(Ts,ps,hV,'r')
ax.set_xlabel('T')
ax.set_ylabel('p')
ax.set_zlabel('enthalpy')

f = plt.figure(3)
ax = f.add_subplot(111,projection='3d')
ax.plot_surface(T,p,s)
ax.plot(Ts,ps,sL,'r')
ax.plot(Ts,ps,sV,'r')
ax.set_xlabel('T')
ax.set_ylabel('p')
ax.set_zlabel('entropy')

f = plt.figure(4)
ax = f.add_subplot(111,projection='3d')
ax.plot_surface(T,p,e)
ax.plot(Ts,ps,eL,'r')
ax.plot(Ts,ps,eV,'r')
ax.set_xlabel('T')
ax.set_ylabel('p')
ax.set_zlabel('energy')

plt.show(block=False)

TypeError: _sat_argparse() got an unexpected keyword argument 'tp'